### ISSUE TITLE
paladin align -o

### ISSUE THREAD

**Issue by macmanes** [twestbrookunh/paladin#19]
`-o` does not seem to be parsed properly. setting it to `-o 100` has no effect on number of reads mapped.

**Comment by twestbrookunh** [comment]
Sorry - my bad again - the minimum ORF length functionality still isn't active, I just forgot to remove the description from the help file for now.  I have an update I'm going to try to release tonight, and I'll incorporate that in for now (more on that later today)

**Comment by macmanes** [comment]
About release: let's see if we can validate the permissive align settings  `-B0 -O0 -E0 -L0` with the @Vadavim scoring code and if they look make these the default settings.

**Comment by twestbrookunh** [comment]
Description removed for now - the next release this/next week (0.3.0) will bring back minimum ORF length - we can test fully and discuss the results

**Comment by Louisa-Normington** [comment]
Where is the sam file for -B0 -O0 -E0 -L0 located? Jordan needs to use it for his script.
