### ISSUE TITLE
Align protein sequences

### ISSUE THREAD

**Issue by abremges** [twestbrookunh/paladin#28]
I have a multi-FASTA file containing protein sequences, that I wish to align w/ PALADIN, i.e. neither the ORF detection step nor a translation to proteins is needed, only the alignment and reporting step.

From my understanding of the PALADIN pipeline, this should be possible, but apparently the functionality is not exposed to the user – correct me if I'm wrong. How do you advise to proceed?

**Comment by twestbrookunh** [comment]
This is good to go now - you can use the "-p" option with the alignment command - it will treat the input sequence as a protein multiFASTA, will skip ORF detection/translation, and jump right to the alignment phase. Thanks!

**Comment by abremges** [comment]
Thank you! 👍 This also solves #24 (at least for me), gene prediction and abundance estimation can be outsourced...
