### ISSUE TITLE
Columns ID to Cross Reference(EnsemblBacteria) are empty

### ISSUE THREAD

**Issue by kdutrufen** [twestbrookunh/paladin#36]
Hi,

paladin is not retrieving information from columns ID to Cross Reference(EnsemblBacteria), like this example, with "test"

Count	Abundance	Quality (Avg)	Quality (Max)	UniProtKB	ID	Organism	Protein Names	Genes	Pathway	Features	Gene Ontology	Reviewed	Existence	Comments	Cross Reference (KEGG)	Cross Reference (GeneID)	Cross Reference (PATRIC)	Cross Reference(EnsemblBacteria)
2	66.66667	0.00000	0	Y1118_DICDI
1	33.33334	0.00000	0	SRGN_RAT

**Comment by twestbrookunh** [comment]
Hi - I just posted version 1.4.3, give that a try when you have a moment and let me know if it fixes the issue.  Uniprot recently updated their webservers to only accept HTTPS traffic, and PALADIN was still set to request URLs via HTTP, so all the calls were failing. Feel free to reopen if it's still having an issue.

**Comment by kdutrufen** [comment]
Thank you very much, it worked.
