### ISSUE TITLE
make returns error (OSX 10.12.6)

### ISSUE THREAD

**Issue by tkkanno** [twestbrookunh/paladin#37]
Hi,

OSx 10.12.6 when I attempt to make palandin I get this error:

gcc -c -g -Wall -Wno-unused-function -O2  -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  translations.c -o translations.o
translations.c:46:9: warning: implicit declaration of function 'renderTranslations' is invalid in C99
      [-Wimplicit-function-declaration]
        renderTranslations();
        ^

**Comment by taylorreiter** [comment]
I received the same error, on OSX 10.13.6

**Comment by twestbrookunh** [comment]
These warning messages should now be fixed in version 1.4.4.  Let me know if you're still having issues compiling.  Thanks
